### ISSUE TITLE
Weather won't load

### ISSUE THREAD

**Issue by dsouzadrian** [jclarke0000/MMM-OpenWeatherForecast#22]
Not sure what happened, but the weather wont load anymore at the turn of the new year.

Following is what shows on the Magic Mirror display

![image](https://user-images.githubusercontent.com/8682704/210406570-081dcbf3-ea66-4d0d-9df4-7b227543bdff.png)

Below are the logs on the client side - nothing stands out to me

![image](https://user-images.githubusercontent.com/8682704/210406638-ae18c108-9029-41c4-81a1-3f91e796df6c.png)

Below are the logs from the server 

```
[03.01.2023 11:09.01.532] [ERROR] TypeError: Cannot read properties of undefined (reading 'get')
    at Class.socketNotificationReceived (/opt/magic_mirror/modules/MMM-OpenWeatherForecast/node_helper.js:57:15)
    at Socket.<anonymous> (/opt/magic_mirror/js/node_helper.js:108:11)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (/opt/magic_mirror/node_modules/socket.io/dist/typed-events.js:69:22)
    at /opt/magic_mirror/node_modules/socket.io/dist/socket.js:614:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

Below is my config:

```
{
	module: "MMM-OpenWeatherForecast",
	position: "bottom_left",
	header: "Forecast",
	config: {
			apikey: "********", //only string here
			latitude: **,            //number works here
			longitude: **,          //so does a string
			showSummary: false,
			iconset: "3c",
			forecastHeaderText: "Forecast at Home",
			showExtraCurrentConditions: true,
			showHourlyForecast: false,
			units: "metric",
			concise: true,
	}
},
```

**Comment by dsouzadrian** [comment]
doing an ```npm install``` fixed the issue
